version: 0.2

env:
  variables:
    S3_BUCKET: "game-changer-tms"
    BUILD_TYPE: "Build"
    BRANCH_NAME: "release"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - buildExitCode=1
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - buildExitCode=$?

    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - echo "exit code $buildExitCode | S3_BUCKET ${S3_BUCKET} | BUILD_TYPE ${BUILD_TYPE} | BRANCH_NAME ${BRANCH_NAME}"
      - curl -s "https://img.shields.io/badge/${BUILD_TYPE}-${badge_status}-${badge_colour}.svg" > ${BRANCH_NAME}-${BUILD_TYPE}.svg
      - echo "${BUILD_TYPE} badge -> s3://${S3_BUCKET}/badges/${BRANCH_NAME}-${BUILD_TYPE}.svg"
      - aws s3 cp ${BRANCH_NAME}-${BUILD_TYPE}.svg s3://${S3_BUCKET}/badges/${BRANCH_NAME}-${BUILD_TYPE}.svg --acl public-read --cache-control no-cache

  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: "dist/gameChanger"
