version: 0.2

env:
  variables:
    S3_BUCKET: "game-changer-tms"
    BUILD_TYPE: "Build"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - buildExitCode=1
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - buildExitCode=$?

    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - branchName=`git rev-parse --abbrev-ref HEAD`
      - curl -s "https://img.shields.io/badge/${BUILD_TYPE}-${badge_status}-${badge_colour}.svg" > ${branchName}-${BUILD_TYPE}.svg
      - aws s3 cp ${branchName}-${BUILD_TYPE}.svg s3://${S3_Bucket}/badges/${branchName}-${BUILD_TYPE}.svg --acl public-read --cache-control no-cache
      - echo "${BUILD_TYPE} badge -> s3://${S3_Bucket}/badges/${branchName}-${BUILD_TYPE}.svg"

  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: "dist/gameChanger"
