version: 0.2
phases:
  install:
    commands:
      # Update libs
      - apt-get update

      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb

      # Install project dependencies
      - npm install

  pre_build:
    commands:
      - buildExitCode=1

  build:
    commands:
      # Build the project
      - npm run test:ci
      - buildExitCode=$?

    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - curl -s "https://img.shields.io/badge/Unittest-${badge_status}-${badge_colour}.svg" > ${GithubBranch}-unittest.svg
      - aws s3 cp ${GithubBranch}-unittest.svg s3://${S3_Bucket}/badges/${GithubBranch}-unittest.svg --acl public-read --cache-control no-cache
      - echo "unittest badge -> s3://${S3_Bucket}/badges/${GithubBranch}-unittest.svg"

  post_build:
    commands:
      - printenv
artifacts:
  files:
    - src/*
