version: 0.2

env:
  variables:
    S3_BUCKET: "game-changer-tms"
    BUILD_TYPE: "Unittest"
    BRANCH_NAME: "release"
phases:
  install:
    commands:
      # Update libs
      - apt-get update

      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb

      # Install project dependencies
      - npm install

  pre_build:
    commands:
      - buildExitCode=1

  build:
    commands:
      # Build the project
      - npm run test:ci
      - buildExitCode=$?

    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - echo "exit code: $buildExitCode"
      - echo "S3_BUCKET: ${S3_BUCKET} | BUILD_TYPE: ${BUILD_TYPE} | BRANCH_NAME: ${BRANCH_NAME}"
      - curl -s "https://img.shields.io/badge/${BUILD_TYPE}-${badge_status}-${badge_colour}.svg" > ${BRANCH_NAME}-${BUILD_TYPE}.svg
      - aws s3 cp ${BRANCH_NAME}-${BUILD_TYPE}.svg s3://${S3_Bucket}/badges/${BRANCH_NAME}-${BUILD_TYPE}.svg --acl public-read --cache-control no-cache
      - echo "${BUILD_TYPE} badge -> s3://${S3_Bucket}/badges/${BRANCH_NAME}-${BUILD_TYPE}.svg"

  post_build:
    commands:
      - printenv
artifacts:
  files:
    - src/*
