version: 0.2
phases:
  install:
    commands:
      # Update libs
      - apt-get update

      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb

      # Install project dependencies
      - npm install

  pre_build:
    commands:
      - echo "Nothing to pre_build"

  build:
    commands:
      # Build the project
      - npm run test:ci

  post_build:
    commands:
      - printenv
artifacts:
  files:
    - src/*
